<!-- markdownlint-disable -->

<a href="../carto_auth/errors.py#L0"><img align="right" style="float:right;" src="https://img.shields.io/badge/-source-cccccc?style=flat-square"></a>

# <kbd>module</kbd> `errors`






---

<a href="../carto_auth/errors.py#L4"><img align="right" style="float:right;" src="https://img.shields.io/badge/-source-cccccc?style=flat-square"></a>

## <kbd>class</kbd> `CredentialsError`







---

<a href="../carto_auth/errors.py#L5"><img align="right" style="float:right;" src="https://img.shields.io/badge/-source-cccccc?style=flat-square"></a>

### <kbd>method</kbd> `from_http_error`

```python
from_http_error(http_error: HTTPError)
```








